bases:
- "../../base"
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
replicas:
- name: "loans-api"
  count: 2
patches:
- patch: "- op: add\n  path: /spec/template/spec/containers/0/env\n  value:\n    -\
    \ name: ENVIRONMENT\n      value: \"dev\""
  target:
    kind: "Deployment"
    name: "loans-api"
- patch: "- op: add\n  path: /data/ENVIRONMENT\n  value: \"dev\""
  target:
    kind: "ConfigMap"
    name: "loans-api-config"
namespace: "loans"
