bases:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
replicas:
- name: loans-api
  count: 1
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
        - name: ENVIRONMENT
          value: "dev"
  target:
    kind: Deployment
    name: loans-api
- patch: |-
    - op: add
      path: /data/ENVIRONMENT
      value: "dev"
  target:
    kind: ConfigMap
    name: loans-api-config
namespace: loans
